# fly.toml app configuration file generated for user-api-u1 on 2023-08-08T12:08:44+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "user-api-u1"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
